/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AsideMenu: typeof import('./src/framework/core/layout/home/AsideMenu.vue')['default']
    BookMark: typeof import('./src/framework/core/layout/home/BookMark.vue')['default']
    Default: typeof import('./src/framework/core/layout/default/index.vue')['default']
    Footer: typeof import('./src/framework/core/layout/home/Footer.vue')['default']
    Header: typeof import('./src/framework/core/layout/home/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/framework/core/layout/home/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RouterWrapper: typeof import('./src/components/layouts/RouterWrapper.vue')['default']
    TestAggrid: typeof import('./src/components/TestAggrid.vue')['default']
    VApp: typeof import('vuetify/lib')['VApp']
    VAppBar: typeof import('vuetify/lib')['VAppBar']
    VAppBarNavIcon: typeof import('vuetify/lib')['VAppBarNavIcon']
    VAvatar: typeof import('vuetify/lib')['VAvatar']
    VBadge: typeof import('vuetify/lib')['VBadge']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VCard: typeof import('vuetify/lib')['VCard']
    VCol: typeof import('vuetify/lib')['VCol']
    VDivider: typeof import('vuetify/lib')['VDivider']
    VFooter: typeof import('vuetify/lib')['VFooter']
    VIcon: typeof import('vuetify/lib')['VIcon']
    VImg: typeof import('vuetify/lib')['VImg']
    VLayout: typeof import('vuetify/lib')['VLayout']
    VList: typeof import('vuetify/lib')['VList']
    VListGroup: typeof import('vuetify/lib')['VListGroup']
    VListItem: typeof import('vuetify/lib')['VListItem']
    VListItemAvatar: typeof import('vuetify/lib')['VListItemAvatar']
    VListItemContent: typeof import('vuetify/lib')['VListItemContent']
    VListItemIcon: typeof import('vuetify/lib')['VListItemIcon']
    VListItemSubtitle: typeof import('vuetify/lib')['VListItemSubtitle']
    VListItemTitle: typeof import('vuetify/lib')['VListItemTitle']
    VMain: typeof import('vuetify/lib')['VMain']
    VMenu: typeof import('vuetify/lib')['VMenu']
    VNavigationDrawer: typeof import('vuetify/lib')['VNavigationDrawer']
    VRow: typeof import('vuetify/lib')['VRow']
    VSheet: typeof import('vuetify/lib')['VSheet']
    VSpacer: typeof import('vuetify/lib')['VSpacer']
    VSubheader: typeof import('vuetify/lib')['VSubheader']
    VTab: typeof import('vuetify/lib')['VTab']
    VTabs: typeof import('vuetify/lib')['VTabs']
    VTabsSlider: typeof import('vuetify/lib')['VTabsSlider']
    VTooltip: typeof import('vuetify/lib')['VTooltip']
  }
}
